USE app;

CREATE TABLE posts
(
  id       INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title    VARCHAR(50),
  body     TEXT,
  created  DATETIME DEFAULT NULL,
  modified DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
